### PR TITLE
Add more details to the website

### PR DESCRIPTION
**Pull request by trallard**
- This creates the pages for the individual sites
- Additional information about the workshop was added:
  - draft agenda
  - purpose of the workshop

Still missing:
- CoC page
- Edit the contents for the Germany site

### CODE REVIEW

**Comment by betatim** [comment]
What do you need in terms of help for the CoC part? There was some discusson/suggestions in https://github.com/betatim/build-a-binder/issues/7#issuecomment-389064416 but it isn't clear to me if people object to the current suggestion or think something else would be an improvement on something which is already Ok.

I'd edit the Germany page to be more of a placeholder and then merge this.

**Comment by gedankenstuecke** [comment]
I think the CoC discussion ended on liking the Mozilla CoC but without identifying the two people who should be the point of contact when issues are raised. 

If no one else volunteers for it I'd step up to be one of the two people. And I'd suggest to get someone from the Mozilla Science Lab/Community to be the second, completely uninvolved person. How does that sound?

**Comment by betatim** [comment]
Sounds good. :+1: to having someone from Mozilla. The other person should be onsite I think. Having two remote CoC contacts seems weird to me.

**Comment by gedankenstuecke** [comment]
True, sounds good to me. In that case I guess you're the one who gets the honor as the person who's guaranteed to be at all of them 😉

**Pull request merged**
